### ISSUE TITLE
Certain wikis are mislabeled as (EN)

### ISSUE THREAD

**Issue by elifoster** [HydraWiki/GlobalWatchlist#1]
I can only really speak for ftb, but labeling it as (EN) is wrong. Perhaps some sort of blacklist could be implemented to override specific elements' label, maybe as (MULTILINGUAL) or something?

**Comment by Alexia** [comment]
The language label is based on the primary display language of the wiki.  Meaning, whatever displays by default.  The language label is fairly specific to how Extension:DynamicSettings does things and would need a decent amount of work to make it happen.

**Comment by elifoster** [comment]
You could check to see if Translate/MLEB extensions are installed and use (MULTI) based on that.

**Comment by xbony2** [comment]
The FTB Wiki is the only wiki that uses MLEB (or at least at the moment).
